version: '3.7'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  DB:
      driver: local
      driver_opts:
        type: none
        device: /home/ebelkhei/data/dbvol
        o: bind
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/ebelkhei/data/wpvol
      o: bind

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    hostname: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - DB:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
            - WP_DB_HOST=mariadb:3306
            - WP_DB_USER=$MYSQL_USER
            - WP_DB_PASSWORD=$MYSQL_PASSWORD
            - WP_DB_NAME=${MYSQL_DATABASE}
            - WP_URL=${WP_URL}
            - WP_TITLE=${WP_TITLE}
            - WP_ADMIN_USER=${WP_ADMIN_USER}
            - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
            - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
            - WP_USER=${WP_USER}
            - WP_USER_EMAIL=${WP_USER_EMAIL}
            - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    networks:
      - inception
    volumes:
      - WordPress:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - adminer
      # - static-website
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - WordPress:/var/www/html

  # Bonus
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    hostname: redis
    restart: always
    # ports:
    #   - "6379:6379"
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    hostname: ftp
    container_name: ftp
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    volumes:
      - WordPress:/var/www/html
    ports:
      - "21:21"
    networks:
      - inception

  static-website:
    build: ./requirements/bonus/static-website
    container_name: static-website
    restart: always
    ports:
      - 3000:3000
    networks:
      - inception
    
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    hostname: adminer
    # ports:
      # - "9000:9000"
    restart: always
    networks:
      - inception

  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    ports:
      - "8080:8080"
    restart: always
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
